project_id = "vwpeuejdgyjcwcymzjxt"

[functions.stripe-webhook]
verify_jwt = false

[functions.reservation-create]
verify_jwt = false

[functions.reservation-get]
verify_jwt = false

[functions.reservation-upload-id]
verify_jwt = false

[functions.contract-api]
verify_jwt = false

[functions.reservation-update]
verify_jwt = false